// File generated by Antigravity based on user input
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // TODO: Add other platforms (Android/iOS) configurations here if needed.
    // unlikely to work on Android without google-services.json anyway.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
         // For Android, usually google-services.json handles this if this is missing, 
         // but explicitly defining it here is better if you have the values.
         // Since we only have Web values, we'll throw or return web values (which might fail).
         throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'please ensure you have google-services.json in android/app/ or configure this file.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'please ensure you have GoogleService-Info.plist in ios/Runner/ or configure this file.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3eejLvTNq-gUMsjjkbS2LxPdRSY1K2PI',
    appId: '1:149470308267:web:535251ac929f82879554ee',
    messagingSenderId: '149470308267',
    projectId: 'labsense-6ef66',
    authDomain: 'labsense-6ef66.firebaseapp.com',
    storageBucket: 'labsense-6ef66.firebasestorage.app',
    measurementId: 'G-7789HFJ8D6',
  );
}
