import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'models.dart';
import 'package:intl/intl.dart';

class PdfService {
  static Future<void> generateLabReportPdf(LabReport report, List<TestResult> results) async {
    final pdf = pw.Document();

    final fontData = await PdfGoogleFonts.interRegular();
    final fontBoldData = await PdfGoogleFonts.interBold();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            _buildHeader(report, fontBoldData),
            pw.SizedBox(height: 24),
            _buildUserInfo(fontBoldData),
            pw.SizedBox(height: 24),
            _buildResultsTable(results, fontData, fontBoldData),
            pw.Spacer(),
            _buildFooter(fontData),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'LabReport_${report.id}.pdf',
    );
  }

  static Future<void> generateSummaryPdf(List<LabReport> reports, {String? aiSummary}) async {
    final pdf = pw.Document();
    final fontData = await PdfGoogleFonts.interRegular();
    final fontBoldData = await PdfGoogleFonts.interBold();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            _buildMedicalHeader(fontBoldData),
            pw.SizedBox(height: 24),
            _buildUserInfo(fontBoldData),
            pw.SizedBox(height: 24),
            
            if (aiSummary != null && aiSummary.isNotEmpty) ...[
              pw.Text('CLINICAL SUMMARY', style: pw.TextStyle(font: fontBoldData, fontSize: 10, color: PdfColors.blue900)),
              pw.SizedBox(height: 8),
              pw.Container(
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.blue100),
                  color: PdfColors.blue50,
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                ),
                child: pw.Text(aiSummary, style: const pw.TextStyle(fontSize: 11, lineSpacing: 2)),
              ),
              pw.SizedBox(height: 24),
            ],

            pw.Text('LABORATORY HISTORY', style: pw.TextStyle(font: fontBoldData, fontSize: 10, color: PdfColors.blue900)),
            pw.SizedBox(height: 12),
            
            for (var report in reports) ...[
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(vertical: 8),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(report.labName, style: pw.TextStyle(font: fontBoldData, fontSize: 12)),
                    pw.Text(DateFormat('MMM d, yyyy').format(report.date), style: const pw.TextStyle(fontSize: 10)),
                  ],
                ),
              ),
              if (report.testResults != null)
                _buildResultsTable(report.testResults!, fontData, fontBoldData),
              pw.SizedBox(height: 24),
            ],
            
            pw.SizedBox(height: 20),
            pw.Divider(color: PdfColors.grey300),
            pw.SizedBox(height: 10),
            pw.Text('DISCLAIMER: This report is generated by LabSense AI for educational purposes only and should not be used as a substitute for professional medical advice, diagnosis, or treatment. Please review these results with your healthcare provider.', 
              style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600, font: fontData)),
            
            pw.Spacer(),
            _buildFooter(fontData),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Professional_Health_Summary_${DateFormat('yyyyMMdd').format(DateTime.now())}.pdf',
    );
  }

  static pw.Widget _buildMedicalHeader(pw.Font boldFont) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('LabSense', style: pw.TextStyle(font: boldFont, fontSize: 28, color: PdfColors.blue900)),
            pw.Text('Advanced Health Intelligence', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
          ],
        ),
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.end,
          children: [
            pw.Text('MEDICAL SUMMARY REPORT', style: pw.TextStyle(font: boldFont, fontSize: 12, color: PdfColors.grey700)),
            pw.Text('ID: LS-${DateFormat('yyyyMM').format(DateTime.now())}-9928', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildHeader(LabReport report, pw.Font boldFont) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('LabSense Report', style: pw.TextStyle(font: boldFont, fontSize: 24, color: PdfColors.blue900)),
            pw.SizedBox(height: 4),
            pw.Text('Generated on ${DateFormat('MMM d, yyyy').format(DateTime.now())}', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
          ],
        ),
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.end,
          children: [
            pw.Text(report.labName, style: pw.TextStyle(font: boldFont, fontSize: 14)),
            pw.Text('Report Date: ${DateFormat('MMM d, yyyy').format(report.date)}', style: const pw.TextStyle(fontSize: 12)),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildUserInfo(pw.Font boldFont) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('PATIENT INFORMATION', style: pw.TextStyle(font: boldFont, fontSize: 8, color: PdfColors.grey700)),
              pw.SizedBox(height: 4),
              pw.Text('Krishna Modi', style: pw.TextStyle(font: boldFont, fontSize: 12)),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('ACCOUNT TYPE', style: pw.TextStyle(font: boldFont, fontSize: 8, color: PdfColors.grey700)),
              pw.SizedBox(height: 4),
              pw.Text('LabSense Personal', style: pw.TextStyle(fontSize: 12)),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildResultsTable(List<TestResult> results, pw.Font font, pw.Font boldFont) {
    final headers = ['Test Name', 'Result', 'Unit', 'Reference Range', 'Status'];

    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: results.map((r) => [
        r.name,
        r.result,
        r.unit,
        r.reference,
        r.status,
      ]).toList(),
      headerStyle: pw.TextStyle(font: boldFont, color: PdfColors.white, fontSize: 10),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.blue900),
      cellStyle: pw.TextStyle(font: font, fontSize: 10),
      cellAlignment: pw.Alignment.centerLeft,
      oddRowDecoration: const pw.BoxDecoration(color: PdfColors.grey50),
      columnWidths: {
        0: const pw.FlexColumnWidth(3),
        1: const pw.FlexColumnWidth(1.5),
        2: const pw.FlexColumnWidth(1.5),
        3: const pw.FlexColumnWidth(2),
        4: const pw.FlexColumnWidth(1.5),
      },
      border: null,
      cellPadding: const pw.EdgeInsets.all(8),
    );
  }

  static pw.Widget _buildFooter(pw.Font font) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 24),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300, width: 0.5)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('LabSense AI - Advanced Health Insights', style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey500)),
          pw.Text('Page 1 of 1', style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey500)),
        ],
      ),
    );
  }
}
