import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../supabase_service.dart';
import '../models.dart';
import '../providers/core_providers.dart';

final medicationRepositoryProvider = Provider<MedicationRepository>((ref) {
  return MedicationRepository(ref.watch(supabaseServiceProvider));
});

class MedicationRepository {
  final SupabaseService _supabaseService;

  MedicationRepository(this._supabaseService);

  Future<List<Medication>> getMedications({String? profileId}) async {
    final data = await _supabaseService.getMedications(profileId: profileId);
    return data.map((json) => Medication.fromJson(json)).toList();
  }

  Future<void> createMedication(Medication medication) async {
    // Convert to JSON but remove ID if it's generated by DB, or keep if UUID generated locally.
    // Model uses local UUID usually.
    final json = medication.toJson();

    // Handle schedules separately for the structure expected by SupabaseService.createMedication
    // The service expects 'reminder_schedules' key in the map if we want it to handle sub-inserts.
    if (medication.schedules != null) {
      json['reminder_schedules'] = medication.schedules!
          .map((s) => s.toJson())
          .toList();
    }

    await _supabaseService.createMedication(json);
  }

  Future<void> updateMedication(Medication medication) async {
    final json = medication.toJson();
    if (medication.schedules != null) {
      json['reminder_schedules'] = medication.schedules!
          .map((s) => s.toJson())
          .toList();
    }
    await _supabaseService.updateMedication(medication.id, json);
  }

  Future<void> deleteMedication(String id) async {
    await _supabaseService.deleteMedication(id);
  }
}
